# Generated by Django 4.2.1 on 2023-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_id', models.CharField(max_length=100)),
                ('std_name', models.CharField(max_length=100)),
                ('std_dob', models.CharField(max_length=50)),
                ('std_school', models.CharField(max_length=50)),
                ('std_email', models.CharField(max_length=45)),
                ('std_address', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=50)),
            ],
        ),
    ]
