# Generated by Django 4.2.1 on 2023-06-04 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_admission_no',
            new_name='admission_no',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_dob',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='std_school',
            new_name='school',
        ),
    ]
