# Generated by Django 4.2.1 on 2023-06-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_principal_season_alter_student_admission_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='issued_date',
        ),
    ]
